### ISSUE TITLE
lut_conf does not build 

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/axiom-beta-firmware#118]
The remote beta is currently on 6be3f4cd-dirty.

The directory /opt/axiom-firmware/software/processing_tools/lut_conf/ contains no binary

Trying to build it shows:

make
gcc -ggdb -Wall -std=gnu99 -O2   -c -o lut_conf.o lut_conf.c
lut_conf.c:15:10: fatal error: iostream: No such file or directory
 #include <iostream>
          ^~~~~~~~~~
compilation terminated.
make: *** [<builtin>: lut_conf.o] Error 1

**Comment by rroohhh** [comment]
Ok, no idea, where the `#include <iostream>` line came from (its not present in the source on github) and why the binary vanished as according to the build log, `lut_conf` was sucessfully built. 

I also double checked the newest version and `lut_conf` is also built sucessfully there, so considering there is now a `lut_conf` binary on the remote beta I would see this fixed.

**Comment by sp-apertus** [comment]
Thanks, will flash latest firmware soon.
