### ISSUE TITLE
Add apertus ssh keys to the Camera

### ISSUE THREAD

**Issue by anuejn** [apertus-open-source-cinema/axiom-beta-firmware#13]
Bertl suggested adding some default keys to the beta images. This would be convenient during development.

**Comment by rroohhh** [comment]
A better solution would maybe be a overlay directory with files that get copied to the root filesystem during image creation, this would solve security / privacy issues connected with shipping a default key. It also allows users / developers to easily add their own system configuration to the images (default shell, shell config, custom bitstreams, own tools, etc).

**Comment by sp-apertus** [comment]
Sounds like a good idea.

**Comment by anuejn** [comment]
this is possible with the overlay feature introduced to the build system

**Comment by rroohhh** [comment]
In addition to that see #65 for the remote debugging aspect of this.
