### ISSUE TITLE
rename kick > start

### ISSUE THREAD

**Issue by sp-apertus** [apertus-open-source-cinema/axiom-beta-firmware#22]
to make it easier for people to understand what these scripts do rename:
kick.sh -> autostart.sh
kick_manual.sh -> start.sh
halt_manual.sh -> stop.sh

**Comment by jatha** [comment]
start what? stop what? maybe start-$task and stop-$task would be more helpful?

**Comment by sp-apertus** [comment]
kick_manual.sh currently initializes the image sensor communication, HDMI output generation and the continuous image capture for the video stream.

**Comment by jatha** [comment]
then mabe all the scripts start_camera.sh stop_camera.sh and autostart_camera.sh?

**Comment by sp-apertus** [comment]
since the service that runs these scripts is called "cmv12k" - and the scripts and service are image sensor specific we could also call it "start_cmv12000.sh"? But I understand this is very technical and people working with the camera might not care about the exact model name of the image sensor....

so "start_camera.sh" also sounds reasonable.... on the other hand the entire device is the camera and that is started before already....

**Comment by jatha** [comment]
yeah you are right :). maybe start_cmv would be resonable as well. The term "cmv-" is included in many names and could already be known by users.  would vote for that.

**Comment by anuejn** [comment]
done
