### ISSUE TITLE
add currently missing packages

### ISSUE THREAD

**Issue by rroohhh** [apertus-open-source-cinema/axiom-beta-firmware#78]
missing are  
- lsof
- mlocate
- stress
- screen
- minicom

**Comment by gcolburn** [comment]
I would think these should probably be included since they are documented in the AXIOM Beta/Manual and are useful for wifi:

- iwlist
- wpa_supplicant

Used in the documentation here: [AXIOM Beta/Manual](https://wiki.apertus.org/index.php/AXIOM_Beta/Manual)

**Comment by rroohhh** [comment]
sure, we should also consider making using wifi and creating wifi hotspots a bit easier for users.
I think `wicd` or `NetworkManager` could be good solutions for the client side.
For creating wifi hotspots we already have started some work in #85.

Also the documentation should probably be updated to for example use `ip` instead of `ifconfig` as the latter is deprecated.
