### ISSUE TITLE
/etc/environment is broken

### ISSUE THREAD

**Issue by rroohhh** [apertus-open-source-cinema/axiom-beta-firmware#98]
It does not work the way it is currently used, as it does not support variables and is actually handled by `pam` and not an actual shell.
```sh
echo 'PATH=${PATH}:/usr/axiom/bin' >> /etc/environment
```
 This manifests itself for example in `scp` not working.

It is unclear if there is something that actually does what we wanted `/etc/environment` to do.

**Comment by anuejn** [comment]
well some sed on that file intead of that append should be fine :)

**Comment by rroohhh** [comment]
Nope, because empty per default. I don't actually know where the default `PATH` is coming from.

**Comment by anuejn** [comment]
ah shit... i see

**Comment by rroohhh** [comment]
We should fix this sooner rather than later, as currently `scp` is borked and getting files on the camera is a pain.
 Just putting `PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/axiom/bin` in `/etc/environment` works for me at the moment.
Its not that elegant, but maybe good enough?

**Comment by anuejn** [comment]
seems to be okay-ish fixed for now
